#!/usr/bin/env python3
"""
Finance Blog Static Site Generator

A 100% Python-powered static site generator for a finance-themed blog.
No hand-authored HTML or JavaScript - all output is generated by Python.

Uses the Python markdown package to convert Markdown files to HTML.
"""

from datetime import datetime
from pathlib import Path

import markdown


# Configuration
CONTENT_DIR = Path("content")
OUTPUT_DIR = Path("site")
STATIC_DIR = Path("static")
SITE_TITLE = "Finance Insights Blog"
SITE_TAGLINE = "Your trusted source for market analysis and financial news"


# Finance-themed color palette with proportional distribution
# Based on: 57.5% #092234, 15.1% #a82d31, 13.5% #9f6d29, 4.7% #baa98c, 3.5% #32a392
COLORS = {
    # Primary (57.5%) - Dark blue for backgrounds
    "bg_dark": "#092234",
    "bg_nav": "#092234",
    
    # Secondary backgrounds
    "bg_card": "#424237",        # Dark olive for cards (2.4%)
    "bg_card_alt": "#1f5b67",    # Dark teal alternative (1.3%)
    
    # Accent Red (15.1%) - Prominent accents
    "accent_primary": "#a82d31",  # Primary red accent
    "border": "#a82d31",          # Red borders
    "accent_dark_red": "#7c2831", # Dark red variant (1.1%)
    
    # Gold/Brown (13.5%) - Headings, links
    "gold": "#9f6d29",
    "gold_dark": "#634e29",       # Dark brown (1.0%)
    
    # Tan/Beige (4.7%) - Secondary text
    "gold_light": "#baa98c",
    "text_secondary": "#baa98c",
    
    # Teal/Green (3.5%) - Subtle accents
    "accent_teal": "#32a392",
    "link_hover": "#32a392",
    
    # Text colors
    "text_primary": "#ffffff",
}


def get_base_css():
    """Return the complete CSS for the finance-themed blog."""
    return f"""
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: {COLORS['bg_dark']};
            color: {COLORS['text_primary']};
            line-height: 1.7;
            min-height: 100vh;
        }}
        a {{
            color: {COLORS['gold']};
            text-decoration: none;
            transition: color 0.2s ease;
        }}
        a:hover {{
            color: {COLORS['link_hover']};
        }}
        .container {{
            max-width: 1100px;
            margin: 0 auto;
            padding: 0 24px;
        }}
        header {{
            background-color: {COLORS['bg_nav']};
            padding: 24px 0;
            border-bottom: 2px solid {COLORS['gold']};
            position: sticky;
            top: 0;
            z-index: 100;
        }}
        header .container {{
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .logo-link {{
            display: flex;
            align-items: center;
            text-decoration: none;
        }}
        .logo-img {{
            height: 48px;
            width: auto;
            margin-right: 12px;
        }}
        .logo {{
            font-size: 1.75rem;
            font-weight: 700;
            color: {COLORS['gold']};
            letter-spacing: 1px;
        }}
        .logo span {{
            color: {COLORS['text_primary']};
        }}
        nav a {{
            margin-left: 28px;
            color: {COLORS['text_secondary']};
            font-weight: 500;
            transition: color 0.2s ease;
        }}
        nav a:hover {{
            color: {COLORS['gold']};
        }}
        .hero {{
            background: linear-gradient(135deg, {COLORS['bg_card']} 0%, {COLORS['bg_dark']} 100%);
            padding: 64px 0;
            text-align: center;
            border-bottom: 1px solid {COLORS['border']};
        }}
        .hero h1 {{
            font-size: 2.75rem;
            color: {COLORS['gold']};
            margin-bottom: 16px;
            text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }}
        .hero p {{
            font-size: 1.2rem;
            color: {COLORS['text_secondary']};
            max-width: 600px;
            margin: 0 auto;
        }}
        main {{
            padding: 48px 0;
        }}
        .posts-list {{
            display: flex;
            flex-direction: column;
            gap: 24px;
        }}
        .post-card {{
            background-color: {COLORS['bg_card']};
            border: 1px solid {COLORS['border']};
            border-left: 4px solid {COLORS['gold']};
            border-radius: 8px;
            padding: 28px 32px;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }}
        .post-card:hover {{
            transform: translateY(-3px);
            box-shadow: 0 8px 24px rgba(0,0,0,0.3);
        }}
        .post-date {{
            font-size: 0.85rem;
            color: {COLORS['gold']};
            font-weight: 600;
            letter-spacing: 0.5px;
            text-transform: uppercase;
        }}
        .post-title {{
            font-size: 1.5rem;
            margin: 10px 0 8px;
            color: {COLORS['text_primary']};
        }}
        .post-title a {{
            color: {COLORS['text_primary']};
        }}
        .post-title a:hover {{
            color: {COLORS['gold']};
        }}
        .post-author {{
            color: {COLORS['text_secondary']};
            font-size: 0.95rem;
        }}
        .post-author strong {{
            color: {COLORS['gold_light']};
        }}
        .article {{
            background-color: {COLORS['bg_card']};
            border-radius: 12px;
            padding: 48px;
            border: 1px solid {COLORS['border']};
        }}
        .article-header {{
            margin-bottom: 36px;
            padding-bottom: 24px;
            border-bottom: 1px solid {COLORS['border']};
        }}
        .article-meta {{
            font-size: 0.9rem;
            color: {COLORS['text_secondary']};
            margin-bottom: 12px;
        }}
        .article-meta .date {{
            color: {COLORS['gold']};
            font-weight: 600;
        }}
        .article h1 {{
            font-size: 2.25rem;
            color: {COLORS['gold']};
            margin-bottom: 8px;
        }}
        .article-content h2 {{
            font-size: 1.5rem;
            color: {COLORS['gold_light']};
            margin: 32px 0 16px;
            padding-bottom: 8px;
            border-bottom: 1px solid {COLORS['border']};
        }}
        .article-content h3 {{
            font-size: 1.25rem;
            color: {COLORS['text_primary']};
            margin: 24px 0 12px;
        }}
        .article-content p {{
            margin-bottom: 16px;
            color: {COLORS['text_secondary']};
        }}
        .article-content ul, .article-content ol {{
            margin: 16px 0 16px 24px;
            color: {COLORS['text_secondary']};
        }}
        .article-content li {{
            margin-bottom: 8px;
        }}
        .article-content code {{
            background-color: {COLORS['bg_dark']};
            padding: 2px 8px;
            border-radius: 4px;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 0.9em;
            color: {COLORS['gold']};
        }}
        .article-content pre {{
            background-color: {COLORS['bg_dark']};
            padding: 20px;
            border-radius: 8px;
            overflow-x: auto;
            margin: 20px 0;
            border: 1px solid {COLORS['border']};
        }}
        .article-content pre code {{
            padding: 0;
            background: none;
        }}
        .article-content blockquote {{
            border-left: 4px solid {COLORS['gold']};
            padding-left: 20px;
            margin: 20px 0;
            font-style: italic;
            color: {COLORS['text_secondary']};
        }}
        .toc {{
            background-color: {COLORS['bg_dark']};
            border: 1px solid {COLORS['border']};
            border-radius: 8px;
            padding: 24px;
            margin-bottom: 32px;
        }}
        .toc h2 {{
            font-size: 1.1rem;
            color: {COLORS['gold']};
            margin-bottom: 16px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }}
        .toc ul {{
            list-style: none;
            margin: 0;
        }}
        .toc li {{
            margin-bottom: 8px;
        }}
        .toc a {{
            color: {COLORS['text_secondary']};
            font-size: 0.95rem;
        }}
        .toc a:hover {{
            color: {COLORS['gold']};
        }}
        .breadcrumb {{
            margin-bottom: 24px;
            font-size: 0.9rem;
        }}
        .breadcrumb a {{
            color: {COLORS['text_secondary']};
        }}
        .breadcrumb span {{
            color: {COLORS['text_secondary']};
            margin: 0 8px;
        }}
        .article-nav {{
            display: flex;
            justify-content: space-between;
            gap: 20px;
            margin-top: 48px;
            padding-top: 24px;
            border-top: 1px solid {COLORS['border']};
        }}
        .article-nav a {{
            background-color: {COLORS['bg_dark']};
            padding: 16px 24px;
            border-radius: 8px;
            border: 1px solid {COLORS['border']};
            flex: 1;
            text-align: center;
            transition: border-color 0.2s ease;
        }}
        .article-nav a:hover {{
            border-color: {COLORS['gold']};
        }}
        footer {{
            background-color: {COLORS['bg_nav']};
            padding: 32px 0;
            text-align: center;
            border-top: 1px solid {COLORS['border']};
            margin-top: 48px;
        }}
        footer p {{
            color: {COLORS['text_secondary']};
            font-size: 0.9rem;
        }}
        @media (max-width: 768px) {{
            .hero h1 {{
                font-size: 2rem;
            }}
            .article {{
                padding: 24px;
            }}
            .article h1 {{
                font-size: 1.75rem;
            }}
            .article-nav {{
                flex-direction: column;
            }}
        }}
    """


def parse_markdown_file(filepath):
    """
    Parse a Markdown file and extract metadata and content.

    Expected format at the top of each file:
        # Post Title
        date: YYYY-MM-DD
        author: Author Name

        Content starts here...
    """
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    title = ""
    date = ""
    author = ""
    content_start = 0

    # Parse header fields
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("# "):
            title = stripped[2:].strip()
        elif stripped.lower().startswith("date:"):
            date = stripped[5:].strip()
        elif stripped.lower().startswith("author:"):
            author = stripped[7:].strip()
        elif stripped == "" and title and date and author:
            content_start = i + 1
            break
        elif i > 10:  # Safety limit for header parsing
            content_start = 0
            break

    # Get the main content (after metadata)
    main_content = "\n".join(lines[content_start:])

    # Convert markdown to HTML
    md = markdown.Markdown(extensions=["extra", "toc"])
    html_content = md.convert(main_content)

    # Extract table of contents
    toc = getattr(md, "toc", "")

    # Generate slug from filename
    slug = Path(filepath).stem

    return {
        "title": title or slug.replace("-", " ").title(),
        "date": date or datetime.now().strftime("%Y-%m-%d"),
        "author": author or "Anonymous",
        "content": html_content,
        "toc": toc,
        "slug": slug,
    }


def generate_html_page(title, body_content, page_type="article"):
    """Generate a complete HTML page with the finance theme."""
    css = get_base_css()

    if page_type == "index":
        nav_links = ""
    else:
        nav_links = '<nav><a href="index.html">Home</a></nav>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | {SITE_TITLE}</title>
    <link rel="icon" type="image/svg+xml" href="favicon.svg">
    <style>{css}</style>
</head>
<body>
    <header>
        <div class="container">
            <a href="index.html" class="logo-link">
                <img src="logo.png" alt="{SITE_TITLE}" class="logo-img" onerror="this.style.display='none'; this.nextElementSibling.style.display='inline';">
                <span class="logo">Finance<span>Insights</span></span>
            </a>
            {nav_links}
        </div>
    </header>
    {body_content}
    <footer>
        <div class="container">
            <p>&copy; {datetime.now().year} {SITE_TITLE}. All rights reserved.</p>
            <p>Generated with Python - No hand-authored HTML or JavaScript.</p>
        </div>
    </footer>
</body>
</html>"""


def generate_index_html(posts):
    """Generate the index.html homepage."""
    # Sort posts by date (newest first)
    sorted_posts = sorted(posts, key=lambda x: x["date"], reverse=True)

    posts_html = ""
    for post in sorted_posts:
        posts_html += f"""
        <article class="post-card">
            <span class="post-date">{post['date']}</span>
            <h2 class="post-title">
                <a href="{post['slug']}.html">{post['title']}</a>
            </h2>
            <p class="post-author">By <strong>{post['author']}</strong></p>
        </article>
        """

    body = f"""
    <section class="hero">
        <div class="container">
            <h1>{SITE_TITLE}</h1>
            <p>{SITE_TAGLINE}</p>
        </div>
    </section>
    <main>
        <div class="container">
            <div class="posts-list">
                {posts_html}
            </div>
        </div>
    </main>
    """

    return generate_html_page(SITE_TITLE, body, page_type="index")


def generate_article_html(post, prev_post=None, next_post=None):
    """Generate an individual article HTML page."""
    toc_html = ""
    if post["toc"]:
        toc_html = f"""
        <div class="toc">
            <h2>Table of Contents</h2>
            {post['toc']}
        </div>
        """

    nav_links = ""
    if prev_post or next_post:
        prev_link = (
            f'<a href="{prev_post["slug"]}.html">&larr; {prev_post["title"]}</a>'
            if prev_post
            else "<span></span>"
        )
        next_link = (
            f'<a href="{next_post["slug"]}.html">{next_post["title"]} &rarr;</a>'
            if next_post
            else "<span></span>"
        )
        nav_links = f"""
        <div class="article-nav">
            {prev_link}
            {next_link}
        </div>
        """

    body = f"""
    <main>
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html">Home</a>
                <span>&raquo;</span>
                <span>{post['title']}</span>
            </div>
            <article class="article">
                <header class="article-header">
                    <div class="article-meta">
                        <span class="date">{post['date']}</span>
                        &bull; By <strong>{post['author']}</strong>
                    </div>
                    <h1>{post['title']}</h1>
                </header>
                {toc_html}
                <div class="article-content">
                    {post['content']}
                </div>
                {nav_links}
            </article>
        </div>
    </main>
    """

    return generate_html_page(post["title"], body, page_type="article")


def build_site():
    """Main function to build the static site."""
    import shutil
    
    print(f"Building {SITE_TITLE}...")

    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Copy static files (favicon, logo) if they exist
    if STATIC_DIR.exists():
        favicon_src = STATIC_DIR / "favicon.svg"
        if favicon_src.exists():
            shutil.copy(favicon_src, OUTPUT_DIR / "favicon.svg")
            print("  Copied: favicon.svg")
        
        logo_src = STATIC_DIR / "logo.png"
        if logo_src.exists():
            shutil.copy(logo_src, OUTPUT_DIR / "logo.png")
            print("  Copied: logo.png")

    # Find all markdown files
    md_files = list(CONTENT_DIR.glob("*.md"))

    if not md_files:
        print("No markdown files found in content/ directory.")
        print("Please add Markdown files to the content/ directory.")
        print("See BLOG_README.md for instructions on adding articles.")
        return

    # Parse all posts
    posts = []
    for md_file in md_files:
        print(f"  Processing: {md_file.name}")
        post = parse_markdown_file(md_file)
        posts.append(post)

    # Sort posts by date
    posts = sorted(posts, key=lambda x: x["date"], reverse=True)

    # Generate index page
    index_html = generate_index_html(posts)
    index_path = OUTPUT_DIR / "index.html"
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_html)
    print(f"  Generated: index.html")

    # Generate individual article pages
    for i, post in enumerate(posts):
        prev_post = posts[i + 1] if i + 1 < len(posts) else None
        next_post = posts[i - 1] if i > 0 else None

        article_html = generate_article_html(post, prev_post, next_post)
        article_path = OUTPUT_DIR / f"{post['slug']}.html"
        with open(article_path, "w", encoding="utf-8") as f:
            f.write(article_html)
        print(f"  Generated: {post['slug']}.html")

    print(f"\nBuild complete! Site generated in '{OUTPUT_DIR}/' directory.")
    print(f"Total articles: {len(posts)}")


if __name__ == "__main__":
    build_site()
