#!/usr/bin/env python3
"""
Finance Blog Static Site Generator

A 100% Python-powered static site generator for a finance-themed blog.
No hand-authored HTML or JavaScript - all output is generated by Python.

Uses the Python markdown package to convert Markdown files to HTML.
"""

import os
import re
from datetime import datetime
from pathlib import Path

import markdown


# Configuration
CONTENT_DIR = Path("content")
OUTPUT_DIR = Path("site")
SITE_TITLE = "Finance Insights Blog"
SITE_TAGLINE = "Your trusted source for market analysis and financial news"


# Finance-themed color palette (dark blue, gold/yellow accents)
COLORS = {
    "bg_dark": "#0a1628",
    "bg_card": "#11243d",
    "bg_nav": "#081020",
    "gold": "#f0b90b",
    "gold_light": "#ffd54f",
    "text_primary": "#ffffff",
    "text_secondary": "#a0b4cc",
    "border": "#1e3a5f",
    "link_hover": "#f5d742",
}


def get_base_css():
    """Return the complete CSS for the finance-themed blog."""
    return f"""
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: {COLORS['bg_dark']};
            color: {COLORS['text_primary']};
            line-height: 1.7;
            min-height: 100vh;
        }}
        a {{
            color: {COLORS['gold']};
            text-decoration: none;
            transition: color 0.2s ease;
        }}
        a:hover {{
            color: {COLORS['link_hover']};
        }}
        .container {{
            max-width: 1100px;
            margin: 0 auto;
            padding: 0 24px;
        }}
        header {{
            background-color: {COLORS['bg_nav']};
            padding: 24px 0;
            border-bottom: 2px solid {COLORS['gold']};
            position: sticky;
            top: 0;
            z-index: 100;
        }}
        header .container {{
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .logo {{
            font-size: 1.75rem;
            font-weight: 700;
            color: {COLORS['gold']};
            letter-spacing: 1px;
        }}
        .logo span {{
            color: {COLORS['text_primary']};
        }}
        nav a {{
            margin-left: 28px;
            color: {COLORS['text_secondary']};
            font-weight: 500;
            transition: color 0.2s ease;
        }}
        nav a:hover {{
            color: {COLORS['gold']};
        }}
        .hero {{
            background: linear-gradient(135deg, {COLORS['bg_card']} 0%, {COLORS['bg_dark']} 100%);
            padding: 64px 0;
            text-align: center;
            border-bottom: 1px solid {COLORS['border']};
        }}
        .hero h1 {{
            font-size: 2.75rem;
            color: {COLORS['gold']};
            margin-bottom: 16px;
            text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }}
        .hero p {{
            font-size: 1.2rem;
            color: {COLORS['text_secondary']};
            max-width: 600px;
            margin: 0 auto;
        }}
        main {{
            padding: 48px 0;
        }}
        .posts-list {{
            display: flex;
            flex-direction: column;
            gap: 24px;
        }}
        .post-card {{
            background-color: {COLORS['bg_card']};
            border: 1px solid {COLORS['border']};
            border-left: 4px solid {COLORS['gold']};
            border-radius: 8px;
            padding: 28px 32px;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }}
        .post-card:hover {{
            transform: translateY(-3px);
            box-shadow: 0 8px 24px rgba(0,0,0,0.3);
        }}
        .post-date {{
            font-size: 0.85rem;
            color: {COLORS['gold']};
            font-weight: 600;
            letter-spacing: 0.5px;
            text-transform: uppercase;
        }}
        .post-title {{
            font-size: 1.5rem;
            margin: 10px 0 8px;
            color: {COLORS['text_primary']};
        }}
        .post-title a {{
            color: {COLORS['text_primary']};
        }}
        .post-title a:hover {{
            color: {COLORS['gold']};
        }}
        .post-author {{
            color: {COLORS['text_secondary']};
            font-size: 0.95rem;
        }}
        .post-author strong {{
            color: {COLORS['gold_light']};
        }}
        .article {{
            background-color: {COLORS['bg_card']};
            border-radius: 12px;
            padding: 48px;
            border: 1px solid {COLORS['border']};
        }}
        .article-header {{
            margin-bottom: 36px;
            padding-bottom: 24px;
            border-bottom: 1px solid {COLORS['border']};
        }}
        .article-meta {{
            font-size: 0.9rem;
            color: {COLORS['text_secondary']};
            margin-bottom: 12px;
        }}
        .article-meta .date {{
            color: {COLORS['gold']};
            font-weight: 600;
        }}
        .article h1 {{
            font-size: 2.25rem;
            color: {COLORS['gold']};
            margin-bottom: 8px;
        }}
        .article-content h2 {{
            font-size: 1.5rem;
            color: {COLORS['gold_light']};
            margin: 32px 0 16px;
            padding-bottom: 8px;
            border-bottom: 1px solid {COLORS['border']};
        }}
        .article-content h3 {{
            font-size: 1.25rem;
            color: {COLORS['text_primary']};
            margin: 24px 0 12px;
        }}
        .article-content p {{
            margin-bottom: 16px;
            color: {COLORS['text_secondary']};
        }}
        .article-content ul, .article-content ol {{
            margin: 16px 0 16px 24px;
            color: {COLORS['text_secondary']};
        }}
        .article-content li {{
            margin-bottom: 8px;
        }}
        .article-content code {{
            background-color: {COLORS['bg_dark']};
            padding: 2px 8px;
            border-radius: 4px;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 0.9em;
            color: {COLORS['gold']};
        }}
        .article-content pre {{
            background-color: {COLORS['bg_dark']};
            padding: 20px;
            border-radius: 8px;
            overflow-x: auto;
            margin: 20px 0;
            border: 1px solid {COLORS['border']};
        }}
        .article-content pre code {{
            padding: 0;
            background: none;
        }}
        .article-content blockquote {{
            border-left: 4px solid {COLORS['gold']};
            padding-left: 20px;
            margin: 20px 0;
            font-style: italic;
            color: {COLORS['text_secondary']};
        }}
        .toc {{
            background-color: {COLORS['bg_dark']};
            border: 1px solid {COLORS['border']};
            border-radius: 8px;
            padding: 24px;
            margin-bottom: 32px;
        }}
        .toc h2 {{
            font-size: 1.1rem;
            color: {COLORS['gold']};
            margin-bottom: 16px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }}
        .toc ul {{
            list-style: none;
            margin: 0;
        }}
        .toc li {{
            margin-bottom: 8px;
        }}
        .toc a {{
            color: {COLORS['text_secondary']};
            font-size: 0.95rem;
        }}
        .toc a:hover {{
            color: {COLORS['gold']};
        }}
        .breadcrumb {{
            margin-bottom: 24px;
            font-size: 0.9rem;
        }}
        .breadcrumb a {{
            color: {COLORS['text_secondary']};
        }}
        .breadcrumb span {{
            color: {COLORS['text_secondary']};
            margin: 0 8px;
        }}
        .article-nav {{
            display: flex;
            justify-content: space-between;
            gap: 20px;
            margin-top: 48px;
            padding-top: 24px;
            border-top: 1px solid {COLORS['border']};
        }}
        .article-nav a {{
            background-color: {COLORS['bg_dark']};
            padding: 16px 24px;
            border-radius: 8px;
            border: 1px solid {COLORS['border']};
            flex: 1;
            text-align: center;
            transition: border-color 0.2s ease;
        }}
        .article-nav a:hover {{
            border-color: {COLORS['gold']};
        }}
        footer {{
            background-color: {COLORS['bg_nav']};
            padding: 32px 0;
            text-align: center;
            border-top: 1px solid {COLORS['border']};
            margin-top: 48px;
        }}
        footer p {{
            color: {COLORS['text_secondary']};
            font-size: 0.9rem;
        }}
        @media (max-width: 768px) {{
            .hero h1 {{
                font-size: 2rem;
            }}
            .article {{
                padding: 24px;
            }}
            .article h1 {{
                font-size: 1.75rem;
            }}
            .article-nav {{
                flex-direction: column;
            }}
        }}
    """


def parse_markdown_file(filepath):
    """
    Parse a Markdown file and extract metadata and content.

    Expected format at the top of each file:
        # Post Title
        date: YYYY-MM-DD
        author: Author Name

        Content starts here...
    """
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    title = ""
    date = ""
    author = ""
    content_start = 0

    # Parse header fields
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("# "):
            title = stripped[2:].strip()
        elif stripped.lower().startswith("date:"):
            date = stripped[5:].strip()
        elif stripped.lower().startswith("author:"):
            author = stripped[7:].strip()
        elif stripped == "" and title and date and author:
            content_start = i + 1
            break
        elif i > 10:  # Safety limit for header parsing
            content_start = 0
            break

    # Get the main content (after metadata)
    main_content = "\n".join(lines[content_start:])

    # Convert markdown to HTML
    md = markdown.Markdown(extensions=["extra", "toc", "codehilite"])
    html_content = md.convert(main_content)

    # Extract table of contents
    toc = getattr(md, "toc", "")

    # Generate slug from filename
    slug = Path(filepath).stem

    return {
        "title": title or slug.replace("-", " ").title(),
        "date": date or datetime.now().strftime("%Y-%m-%d"),
        "author": author or "Anonymous",
        "content": html_content,
        "toc": toc,
        "slug": slug,
    }


def generate_html_page(title, body_content, page_type="article"):
    """Generate a complete HTML page with the finance theme."""
    css = get_base_css()

    if page_type == "index":
        nav_links = ""
    else:
        nav_links = '<nav><a href="index.html">Home</a></nav>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | {SITE_TITLE}</title>
    <style>{css}</style>
</head>
<body>
    <header>
        <div class="container">
            <a href="index.html" class="logo">Finance<span>Insights</span></a>
            {nav_links}
        </div>
    </header>
    {body_content}
    <footer>
        <div class="container">
            <p>&copy; {datetime.now().year} {SITE_TITLE}. All rights reserved.</p>
            <p>Generated with Python - No hand-authored HTML or JavaScript.</p>
        </div>
    </footer>
</body>
</html>"""


def generate_index_html(posts):
    """Generate the index.html homepage."""
    # Sort posts by date (newest first)
    sorted_posts = sorted(posts, key=lambda x: x["date"], reverse=True)

    posts_html = ""
    for post in sorted_posts:
        posts_html += f"""
        <article class="post-card">
            <span class="post-date">{post['date']}</span>
            <h2 class="post-title">
                <a href="{post['slug']}.html">{post['title']}</a>
            </h2>
            <p class="post-author">By <strong>{post['author']}</strong></p>
        </article>
        """

    body = f"""
    <section class="hero">
        <div class="container">
            <h1>{SITE_TITLE}</h1>
            <p>{SITE_TAGLINE}</p>
        </div>
    </section>
    <main>
        <div class="container">
            <div class="posts-list">
                {posts_html}
            </div>
        </div>
    </main>
    """

    return generate_html_page(SITE_TITLE, body, page_type="index")


def generate_article_html(post, prev_post=None, next_post=None):
    """Generate an individual article HTML page."""
    toc_html = ""
    if post["toc"]:
        toc_html = f"""
        <div class="toc">
            <h2>Table of Contents</h2>
            {post['toc']}
        </div>
        """

    nav_links = ""
    if prev_post or next_post:
        prev_link = (
            f'<a href="{prev_post["slug"]}.html">&larr; {prev_post["title"]}</a>'
            if prev_post
            else "<span></span>"
        )
        next_link = (
            f'<a href="{next_post["slug"]}.html">{next_post["title"]} &rarr;</a>'
            if next_post
            else "<span></span>"
        )
        nav_links = f"""
        <div class="article-nav">
            {prev_link}
            {next_link}
        </div>
        """

    body = f"""
    <main>
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html">Home</a>
                <span>&raquo;</span>
                <span>{post['title']}</span>
            </div>
            <article class="article">
                <header class="article-header">
                    <div class="article-meta">
                        <span class="date">{post['date']}</span>
                        &bull; By <strong>{post['author']}</strong>
                    </div>
                    <h1>{post['title']}</h1>
                </header>
                {toc_html}
                <div class="article-content">
                    {post['content']}
                </div>
                {nav_links}
            </article>
        </div>
    </main>
    """

    return generate_html_page(post["title"], body, page_type="article")


def build_site():
    """Main function to build the static site."""
    print(f"Building {SITE_TITLE}...")

    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Find all markdown files
    md_files = list(CONTENT_DIR.glob("*.md"))

    if not md_files:
        print("No markdown files found in content/ directory.")
        print("Creating sample content...")
        create_sample_content()
        md_files = list(CONTENT_DIR.glob("*.md"))

    # Parse all posts
    posts = []
    for md_file in md_files:
        print(f"  Processing: {md_file.name}")
        post = parse_markdown_file(md_file)
        posts.append(post)

    # Sort posts by date
    posts = sorted(posts, key=lambda x: x["date"], reverse=True)

    # Generate index page
    index_html = generate_index_html(posts)
    index_path = OUTPUT_DIR / "index.html"
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_html)
    print(f"  Generated: index.html")

    # Generate individual article pages
    for i, post in enumerate(posts):
        prev_post = posts[i + 1] if i + 1 < len(posts) else None
        next_post = posts[i - 1] if i > 0 else None

        article_html = generate_article_html(post, prev_post, next_post)
        article_path = OUTPUT_DIR / f"{post['slug']}.html"
        with open(article_path, "w", encoding="utf-8") as f:
            f.write(article_html)
        print(f"  Generated: {post['slug']}.html")

    print(f"\nBuild complete! Site generated in '{OUTPUT_DIR}/' directory.")
    print(f"Total articles: {len(posts)}")


def create_sample_content():
    """Create sample blog posts for demonstration."""
    CONTENT_DIR.mkdir(parents=True, exist_ok=True)

    sample_posts = [
        {
            "filename": "market-outlook-2024.md",
            "content": """# 2024 Market Outlook: Navigating Uncertainty
date: 2024-01-15
author: Sarah Chen

As we enter 2024, investors face a complex landscape of opportunities and challenges. This analysis explores the key factors that will shape market performance in the coming year.

## Economic Indicators

The global economy shows mixed signals heading into 2024. While inflation has moderated from its peaks, central banks remain cautious about declaring victory too soon.

### Key Metrics to Watch

- **Inflation rates**: Core CPI trending toward 3%
- **Employment data**: Labor market remains resilient
- **GDP growth**: Moderate expansion expected

## Sector Analysis

Different sectors present varying opportunities for investors:

1. **Technology**: AI-driven growth continues
2. **Healthcare**: Aging demographics drive demand
3. **Energy**: Transition investments accelerate
4. **Financial Services**: Interest rate sensitivity remains

## Investment Strategy

> "In times of uncertainty, diversification becomes even more critical." - Warren Buffett

For 2024, we recommend a balanced approach:

- Maintain diversified portfolio allocation
- Focus on quality companies with strong balance sheets
- Consider defensive positions in volatile markets
- Monitor geopolitical developments closely

## Conclusion

While challenges remain, disciplined investors who maintain their long-term perspective are well-positioned for success in 2024.
""",
        },
        {
            "filename": "cryptocurrency-regulation.md",
            "content": """# The Future of Cryptocurrency Regulation
date: 2024-02-08
author: Michael Torres

Regulatory frameworks for digital assets are evolving rapidly across major economies. Understanding these changes is essential for investors and businesses operating in the crypto space.

## Current Regulatory Landscape

Different jurisdictions have taken varying approaches to cryptocurrency regulation:

### United States

The SEC and CFTC continue to clarify their jurisdiction over different types of digital assets. Key developments include:

- Enhanced reporting requirements for exchanges
- Clarity on security vs. commodity classification
- Stablecoin oversight frameworks

### European Union

The Markets in Crypto-Assets (MiCA) regulation represents the most comprehensive framework to date:

- Licensing requirements for crypto service providers
- Consumer protection standards
- Environmental disclosure requirements

## Impact on Markets

Regulatory clarity brings both challenges and opportunities:

1. **Institutional Adoption**: Clear rules encourage traditional finance participation
2. **Compliance Costs**: Smaller players face increased operational burdens
3. **Market Stability**: Oversight may reduce volatility over time

## Looking Ahead

The trend toward regulation appears irreversible. Market participants should:

- Stay informed about regulatory developments
- Implement robust compliance frameworks
- Consider jurisdiction-specific strategies

> "Regulation isn't the enemy of innovation—it's the foundation of sustainable growth."

## Conclusion

As the crypto industry matures, regulatory frameworks will continue to evolve. Those who adapt proactively will be best positioned for long-term success.
""",
        },
        {
            "filename": "sustainable-investing-guide.md",
            "content": """# A Complete Guide to Sustainable Investing
date: 2024-02-20
author: Emma Rodriguez

Environmental, Social, and Governance (ESG) investing has moved from niche strategy to mainstream approach. This guide explores how to build a portfolio aligned with your values without sacrificing returns.

## Understanding ESG Criteria

ESG factors provide a framework for evaluating companies beyond traditional financial metrics:

### Environmental

- Carbon emissions and climate impact
- Resource efficiency and waste management
- Renewable energy adoption

### Social

- Labor practices and worker safety
- Diversity and inclusion initiatives
- Community engagement

### Governance

- Board composition and independence
- Executive compensation structures
- Shareholder rights protections

## Building Your ESG Portfolio

Follow these steps to construct a sustainable investment strategy:

1. **Define Your Priorities**: Identify which ESG factors matter most to you
2. **Research Options**: Evaluate ESG funds and individual securities
3. **Assess Performance**: Review historical returns and risk metrics
4. **Monitor Holdings**: Track ongoing ESG performance

## Common Misconceptions

Let's address some myths about sustainable investing:

- **Myth**: ESG investing means lower returns
- **Reality**: Studies show competitive performance over time

- **Myth**: ESG is just about excluding "sin stocks"
- **Reality**: Modern ESG focuses on positive selection and engagement

## Available Investment Vehicles

Multiple options exist for ESG-focused investors:

| Type | Advantages | Considerations |
|------|------------|----------------|
| ESG ETFs | Low cost, diversified | Limited customization |
| Mutual Funds | Active management | Higher fees |
| Direct Stocks | Full control | Requires research |

## Conclusion

Sustainable investing offers a path to align financial goals with personal values. With growing data and tools available, building an effective ESG portfolio has never been more accessible.
""",
        },
        {
            "filename": "interest-rate-impact.md",
            "content": """# How Interest Rate Changes Affect Your Portfolio
date: 2024-03-05
author: David Kim

Interest rate decisions by central banks ripple through financial markets, affecting everything from bond prices to stock valuations. Understanding these dynamics is crucial for effective portfolio management.

## The Mechanics of Rate Changes

When central banks adjust interest rates, multiple transmission mechanisms come into play:

### Direct Effects

- **Bond Prices**: Move inversely to interest rates
- **Borrowing Costs**: Affect corporate profitability
- **Currency Values**: Higher rates typically strengthen currencies

### Indirect Effects

1. Consumer spending patterns shift
2. Business investment decisions change
3. Asset allocation preferences evolve

## Asset Class Impacts

Different investments respond uniquely to rate changes:

### Fixed Income

```
Rate Increase → Bond Price Decrease
Rate Decrease → Bond Price Increase
```

Duration measures sensitivity—longer duration means greater impact.

### Equities

Stock sectors respond differently:

- **Growth stocks**: More sensitive to rate increases
- **Value stocks**: May outperform in rising rate environments
- **Dividend stocks**: Competition from higher bond yields

### Real Estate

Property values face pressure from:

- Higher mortgage costs
- Increased capitalization rates
- Reduced affordability

## Portfolio Strategies

Consider these approaches in changing rate environments:

> "Don't try to predict interest rates—position your portfolio to be resilient across scenarios."

### Rising Rate Environment

- Shorten fixed income duration
- Favor floating rate instruments
- Consider financial sector stocks

### Falling Rate Environment

- Extend duration selectively
- Evaluate growth stock opportunities
- Review refinancing options

## Conclusion

Interest rate changes are inevitable. By understanding their effects and maintaining a flexible approach, investors can navigate these shifts successfully.
""",
        },
        {
            "filename": "retirement-planning-basics.md",
            "content": """# Retirement Planning Fundamentals for Every Age
date: 2024-03-18
author: Jennifer Walsh

Regardless of where you are in your career, it's never too early—or too late—to start planning for retirement. This guide provides age-appropriate strategies for building long-term financial security.

## The Power of Starting Early

Time is your greatest asset in retirement planning. Consider the math:

- **Starting at 25**: $500/month at 7% annual return = ~$1.2M by 65
- **Starting at 35**: Same contribution = ~$567K by 65
- **Starting at 45**: Same contribution = ~$245K by 65

## Strategies by Life Stage

### In Your 20s: Foundation Building

Priority actions:

1. Establish emergency fund (3-6 months expenses)
2. Maximize employer 401(k) match
3. Open a Roth IRA
4. Develop good financial habits

### In Your 30s: Acceleration Phase

Key focus areas:

- Increase contribution rates with salary growth
- Diversify investment allocations
- Consider target-date funds for simplicity
- Begin exploring real estate investments

### In Your 40s: Optimization Period

Critical steps:

- Max out all tax-advantaged accounts
- Catch-up contributions become available at 50
- Review and rebalance portfolio allocation
- Plan for healthcare costs in retirement

### In Your 50s and Beyond: Transition Planning

Essential activities:

- Calculate retirement income needs
- Evaluate Social Security claiming strategies
- Consider part-time work transitions
- Plan for Required Minimum Distributions

## Common Retirement Accounts

| Account Type | 2024 Contribution Limit | Tax Treatment |
|--------------|-------------------------|---------------|
| 401(k) | $23,000 | Pre-tax or Roth |
| IRA | $7,000 | Pre-tax or Roth |
| HSA | $4,150 (individual) | Triple tax advantage |

## Avoiding Common Mistakes

Watch out for these retirement planning pitfalls:

- Underestimating healthcare costs
- Taking Social Security too early
- Not accounting for inflation
- Excessive withdrawal rates

> "The best time to plant a tree was 20 years ago. The second best time is now." - Chinese Proverb

## Conclusion

Retirement planning is a marathon, not a sprint. Start where you are, use what you have, and take consistent action toward your financial future.
""",
        },
    ]

    for post in sample_posts:
        filepath = CONTENT_DIR / post["filename"]
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(post["content"])
        print(f"  Created sample: {post['filename']}")


if __name__ == "__main__":
    build_site()
